"""ATAR memory semantic search + skills auto-learning engine.

Memory: upgrades FTS5 with embedding-based semantic search (sentence-transformers).
Skills: detects repeated successful tool patterns and auto-creates skills.
"""

from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field
from typing import Any

# Tool result types (used by memory_semantic tool)
from atar_models.tools import ToolContext, ToolResult

from atar_core.paths import _atar_home as atar_home

# ── Semantic Memory ──

MEMORY_EMBEDDINGS_PATH = os.path.join(atar_home(), "memory_embeddings.json")


@dataclass
class ToolPattern:
    """A detected sequence of tool calls that succeeded."""
    tool_names: list[str] = field(default_factory=list)
    fingerprint: str = ""
    success_count: int = 0
    total_attempts: int = 0
    first_seen: float = 0.0
    last_seen: float = 0.0
    example_prompt: str = ""
    suggested_name: str = ""

    @property
    def success_rate(self) -> float:
        if self.total_attempts == 0:
            return 0.0
        return self.success_count / self.total_attempts

    @property
    def should_create_skill(self) -> bool:
        """A pattern worth creating a skill for: 3+ successes, >70% rate."""
        return self.success_count >= 3 and self.success_rate >= 0.7


_PATTERN_STORE: dict[str, ToolPattern] = {}
_PATTERNS_PATH = os.path.join(atar_home(), "tool_patterns.json")
_RECENT_CALLS: list[dict] = []  # Rolling window of recent tool calls per session


def _fingerprint(tool_names: list[str]) -> str:
    return hashlib.sha256("→".join(tool_names).encode()).hexdigest()[:12]


def _load_patterns() -> dict[str, ToolPattern]:
    global _PATTERN_STORE
    if _PATTERN_STORE:
        return _PATTERN_STORE
    try:
        with open(_PATTERNS_PATH) as f:
            raw = json.load(f)
        _PATTERN_STORE = {k: ToolPattern(**v) for k, v in raw.items()}
    except (FileNotFoundError, json.JSONDecodeError):
        _PATTERN_STORE = {}
    return _PATTERN_STORE


def _save_patterns() -> None:
    os.makedirs(os.path.dirname(_PATTERNS_PATH), exist_ok=True)
    with open(_PATTERNS_PATH, "w") as f:
        json.dump({k: {
            "tool_names": v.tool_names,
            "fingerprint": v.fingerprint,
            "success_count": v.success_count,
            "total_attempts": v.total_attempts,
            "first_seen": v.first_seen,
            "last_seen": v.last_seen,
            "example_prompt": v.example_prompt,
            "suggested_name": v.suggested_name,
        } for k, v in _PATTERN_STORE.items()}, f, indent=2)


def record_tool_pattern(tool_sequence: list[str], prompt: str, all_succeeded: bool) -> None:
    """Record a sequence of tool calls for pattern detection."""
    if len(tool_sequence) < 2:
        return
    if len(tool_sequence) > 8:
        return

    patterns = _load_patterns()
    now = time.time()
    fp = _fingerprint(tool_sequence)

    if fp not in patterns:
        patterns[fp] = ToolPattern(
            tool_names=list(tool_sequence),
            fingerprint=fp,
            first_seen=now,
        )

    p = patterns[fp]
    p.total_attempts += 1
    if all_succeeded:
        p.success_count += 1
    p.last_seen = now
    if prompt:
        p.example_prompt = prompt[:200]

    # Auto-suggest name
    if not p.suggested_name and len(tool_sequence) >= 2:
        p.suggested_name = "auto-" + "-".join(tool_sequence[:3])

    _PATTERN_STORE = patterns  # noqa: N806
    _save_patterns()


def get_ready_skills() -> list[ToolPattern]:
    """Get patterns that are ready to become skills."""
    patterns = _load_patterns()
    return [p for p in patterns.values() if p.should_create_skill]


def generate_skill_draft(pattern: ToolPattern) -> str:
    """Generate a SKILL.md draft from a tool pattern."""
    return f"""---
name: {pattern.suggested_name}
description: Auto-detected pattern: {' → '.join(pattern.tool_names)}
trigger_hints: [{', '.join(pattern.tool_names[:3])}]
auto_generated: true
success_rate: {pattern.success_rate:.0%}
uses: {pattern.total_attempts}
---

# {pattern.suggested_name.replace('-', ' ').title()}

Auto-detected successful tool pattern ({pattern.success_count}/{pattern.total_attempts} attempts).

## Steps

""" + "\n".join(f"{i+1}. Call `{t}`" for i, t in enumerate(pattern.tool_names)) + f"""

## Example Prompt

{pattern.example_prompt}

---
*This skill was auto-generated by ATAR's pattern detection engine.*
"""


# ── Semantic Memory Search ──

def semantic_memory_search(query: str, limit: int = 10) -> list[dict]:
    """Search memory using embeddings for semantic similarity.

    Falls back to FTS5 text search if sentence-transformers not available.
    """
    try:
        import numpy as np
        from sentence_transformers import SentenceTransformer
    except ImportError:
        # Fallback to text-based search
        from atar_core.memory import get_entries
        entries = get_entries(limit=50)
        query_lower = query.lower()
        scored = []
        for e in entries:
            content_lower = e.content.lower()
            # Simple keyword scoring
            score = sum(1 for word in query_lower.split() if word in content_lower)
            if score > 0:
                scored.append((score, e))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [
            {"id": e.id, "category": e.category, "content": e.content,
             "score": s, "method": "keyword"}
            for s, e in scored[:limit]
        ]

    try:
        model = SentenceTransformer("all-MiniLM-L6-v2")
        from atar_core.memory import get_entries

        entries = get_entries(limit=200)
        if not entries:
            return []

        # Load cached embeddings
        embeddings_cache: dict[int, list[float]] = {}
        try:
            with open(MEMORY_EMBEDDINGS_PATH) as f:
                raw = json.load(f)
            embeddings_cache = {int(k): v for k, v in raw.items()}
        except (FileNotFoundError, json.JSONDecodeError):
            pass

        # Embed query
        query_embedding = model.encode(query, convert_to_numpy=True)

        # Score entries
        scored = []
        for e in entries:
            if e.id in embeddings_cache:
                emb = np.array(embeddings_cache[e.id])
            else:
                emb = model.encode(e.content, convert_to_numpy=True)
                embeddings_cache[e.id] = emb.tolist()

            # Cosine similarity
            similarity = float(np.dot(query_embedding, emb) / (np.linalg.norm(query_embedding) * np.linalg.norm(emb) + 1e-8))
            if similarity > 0.1:
                scored.append((similarity, e))

        scored.sort(key=lambda x: x[0], reverse=True)

        # Save updated cache
        os.makedirs(os.path.dirname(MEMORY_EMBEDDINGS_PATH), exist_ok=True)
        with open(MEMORY_EMBEDDINGS_PATH, "w") as f:
            json.dump(embeddings_cache, f)

        return [
            {"id": e.id, "category": e.category, "content": e.content,
             "score": round(s, 3), "method": "semantic"}
            for s, e in scored[:limit]
        ]
    except Exception:
        # Fallback
        from atar_core.memory import get_entries
        entries = get_entries(limit=limit)
        return [
            {"id": e.id, "category": e.category, "content": e.content,
             "score": 0.0, "method": "fallback"}
            for e in entries[:limit]
        ]


# ── Memory semantic search tool registration ──

async def _memory_semantic(_name: str, args: dict[str, Any], ctx: ToolContext) -> ToolResult:  # noqa: F821
    """Semantic search through memories using embeddings."""
    query = args.get("query", "")
    if not query:
        return ToolResult(success=False, error="query required")

    limit = min(args.get("limit", 10), 20)
    results = semantic_memory_search(query, limit)

    if not results:
        return ToolResult(success=True, output="No semantically similar memories found.")

    lines = [f"Semantic search results for '{query}':"]
    for r in results:
        method_tag = f" [{r['method']}]" if r.get("method") != "semantic" else ""
        lines.append(f"  [{r['id']}] [{r['category']}] {r['content'][:100]}{method_tag} (score: {r['score']})")

    return ToolResult(
        success=True,
        output="\n".join(lines),
        metadata={"method": results[0].get("method", "semantic"), "count": len(results)},
    )


# Register memory_semantic tool
try:
    from atar_tools.registry import register as _reg
    _reg(
        "memory_semantic",
        "Semantic memory search using embeddings (falls back to keyword)",
        _memory_semantic,
        parameters={
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Natural language query"},
                "limit": {"type": "integer", "description": "Max results (default 10)"},
            },
            "required": ["query"],
        },
        destructive=False,
        toolset="memory",
    )
except Exception:
    pass
